name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devops-beginner-app .

      - name: Run container
        run: docker run -d -p 5000:5000 --name test-app devops-beginner-app

      - name: Wait for app to start
        run: sleep 10

      - name: Show container logs (debug)
        run: docker logs test-app

      - name: Test app is responding
        run: curl --retry 5 --retry-delay 3 --fail http://localhost:5000

      - name: Stop container
        run: docker stop test-app
